services:
  cronzilla:
    image: ghcr.io/danielproctor31/cronzilla:main
    environment:
      - CRON_INTERVAL='*/5 * * * *'
    container_name: cronzilla
    restart: unless-stopped
    volumes:
      - ./packages.txt:/packages.txt
      - ./run.sh:/cron/run.sh
