services:
  cronzilla:
    build:
      context: .
      args:
        CRON_INTERVAL: '*/5 * * * *'
    container_name: cronzilla
    restart: unless-stopped
    volumes:
      - ./packages.txt:/packages.txt
      - ./run.sh:/cron/run.sh
